# Generated by Django 4.1 on 2023-02-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scoring_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
