# Generated by Django 4.1 on 2023-02-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scoring_app", "0002_delete_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickName", models.CharField(max_length=30)),
                ("fullName", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
