# Generated by Django 4.1 on 2023-02-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scoring_app", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="fullName",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="nickName",
            new_name="nick_name",
        ),
    ]
